### ISSUE TITLE
It has been a year and the author has not disclosed the code as stated in the article

### ISSUE THREAD

**Issue by biosig001** [IoBT-VISTEC/RRWaveNet#2]
![image](https://github.com/IoBT-VISTEC/RRWaveNet/assets/166093330/c5557793-7b90-447b-ab7b-b786005a2a06)
The author did not make the code public as agreed. From a temporal perspective, this could have been a request from the reviewers. Since the paper has already stated that the code would be made public, the author should adhere to this agreement to avoid impacting their own reputation.

**Comment by gunsodo** [comment]
@chris000123 Sorry for the inconvenience, we have just released our source code after improving the code quality. You can now access the code.
